name: Đang khởi tạo RDP Windows mới nhất


on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Đang tải Ngrok cho Windows x64
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Đang giải nén
      run: Expand-Archive ngrok.zip

    - name: Đang thêm Authtoken
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Đang bật Remote Desktop 
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Cấu hình UserAuthentication cho RDP-Tcp
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Tạo người dùng "runneradmin" với mật khẩu "P@ssw0rd!"
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Đang chạy Ngrok và trích xuất public_url
      id: ngrok
      run: |
        $ngrokOutput = .\ngrok\ngrok.exe tcp 3389 -region ap
        $publicUrl = $ngrokOutput -match 'tcp://(.*\.ngrok\.io)'
        if ($Matches.Count -eq 2) {
          Write-Host "Public URL: $($Matches[1])"
          echo "::set-output name=public_url::${Matches[1]}"
        } else {
          Write-Host "Failed to extract Public URL from Ngrok output."
          exit 1
        }

    - name: Sử dụng public_url trong các bước tiếp theo
      run: echo "Public URL is ${{ steps.ngrok.outputs.public_url }}"