name: Đang khởi tạo 


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: windows-2019


    steps:

    - name: Đang tải Ngrok cho Windows x64

      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Đang giải nén

      run: Expand-Archive ngrok.zip

    - name: Đang thêm Authtoken

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Đang bật Remote Desktop và thêm User\Password 

      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Đang thêm password && run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Đã tạo thành công 

      run: .\ngrok\ngrok.exe tcp 3389 -region ap