name: Linux with ngrok

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add ngrok repository
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list

      - name: Update package list
        run: sudo apt update

      - name: Install ngrok
        run: sudo apt install ngrok

      - name: Add auth token
        run: |
          echo "2SshjXEA8sWiijINVW6d9RLwzeQ_2jhoV2iwGN2G65rWpHBoc" | ngrok config add-authtoken

      - name: Start ngrok
        run: |
          ngrok start -p 5900
